// Generated by tools/gen-upcalls.sh from upcalls.txt. Do not edit.
package org.thisisthepy.compose.window.graalvm.macos;

import org.graalvm.nativeimage.IsolateThread;
import org.graalvm.nativeimage.c.function.CEntryPoint;
import org.graalvm.nativeimage.c.function.CEntryPointLiteral;
import org.graalvm.nativeimage.c.function.CFunctionPointer;

/**
 * The addresses the AppKit window calls to reach back into the image.
 *
 * Each address is a {@link CEntryPointLiteral} resolved while the image is built, so a
 * call from C is a plain function call into a static method: no lookup by name, no
 * reflection and no JNI at run time. The static method forwards to a handler slot in
 * {@link AppKitUpcallSlots}, which Kotlin fills in. Nothing may be thrown out of an entry
 * point, because an exception crossing into C is undefined.
 */
public final class AppKitUpcalls {
    private AppKitUpcalls() {
    }

    /** The address of the entry point `dxc_appkit_draw_frame`. */
    public static final CEntryPointLiteral<CFunctionPointer> DRAW_FRAME =
        CEntryPointLiteral.create(AppKitUpcalls.class, "call_frame", IsolateThread.class);

    @CEntryPoint(name = "dxc_appkit_draw_frame")
    static void call_frame(IsolateThread thread) {
        try {
            Runnable handler = AppKitUpcallSlots.INSTANCE.getFrame();
            if (handler != null) {
                handler.run();
            }
        } catch (Throwable failure) {
            failure.printStackTrace();
        }
    }

}
