#!/bin/sh
# Writes AppKitUpcalls.java from upcalls.txt, so the table of entry points is generated
# and never edited by hand. Run with no arguments to rewrite the file, or with --check to
# fail when the checked-in file is stale.
set -eu
here="$(cd "$(dirname "$0")/.." && pwd)"
out="$here/src/org/thisisthepy/compose/window/graalvm/macos/AppKitUpcalls.java"
tmp="$(mktemp)"
{
  cat <<'HEAD'
// Generated by tools/gen-upcalls.sh from upcalls.txt. Do not edit.
package org.thisisthepy.compose.window.graalvm.macos;

import org.graalvm.nativeimage.IsolateThread;
import org.graalvm.nativeimage.c.function.CEntryPoint;
import org.graalvm.nativeimage.c.function.CEntryPointLiteral;
import org.graalvm.nativeimage.c.function.CFunctionPointer;

/**
 * The addresses the AppKit window calls to reach back into the image.
 *
 * Each address is a {@link CEntryPointLiteral} resolved while the image is built, so a
 * call from C is a plain function call into a static method: no lookup by name, no
 * reflection and no JNI at run time. The static method forwards to a handler slot in
 * {@link AppKitUpcallSlots}, which Kotlin fills in. Nothing may be thrown out of an entry
 * point, because an exception crossing into C is undefined.
 */
public final class AppKitUpcalls {
    private AppKitUpcalls() {
    }

HEAD
  grep -v '^#' "$here/upcalls.txt" | while read -r name const slot; do
    [ -n "$name" ] || continue
    method="call_$slot"; cap="$(printf %s "$slot" | awk '{print toupper(substr($0,1,1)) substr($0,2)}')"
    cat <<ENTRY
    /** The address of the entry point \`$name\`. */
    public static final CEntryPointLiteral<CFunctionPointer> $const =
        CEntryPointLiteral.create(AppKitUpcalls.class, "$method", IsolateThread.class);

    @CEntryPoint(name = "$name")
    static void $method(IsolateThread thread) {
        try {
            Runnable handler = AppKitUpcallSlots.INSTANCE.get${cap}();
            if (handler != null) {
                handler.run();
            }
        } catch (Throwable failure) {
            failure.printStackTrace();
        }
    }

ENTRY
  done
  echo "}"
} > "$tmp"
if [ "${1:-}" = "--check" ]; then
  diff -u "$out" "$tmp" >/dev/null || { echo "AppKitUpcalls.java is stale: run tools/gen-upcalls.sh" >&2; rm -f "$tmp"; exit 1; }
  rm -f "$tmp"
else
  mv "$tmp" "$out"
fi
